apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-number-game
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-number-game
  template:
    metadata:
      labels:
        app: flask-number-game
    spec:
      containers:
      - name: flask-number-game
        image: <ACR_NAME>.azurecr.io/flask-number-game:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
