apiVersion: v1
kind: Service
metadata:
  name: flask-number-game-service
  namespace: default
spec:
  selector:
    app: flask-number-game
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
